# Configs
from starlette.config import Config
import cloudinary


config = Config(".env")

DATABASE_URL = config("DATABASE_URL")
GITHUB_CLIENT_ID = config("GITHUB_CLIENT_ID")
GITHUB_CLIENT_SECRET = config("GITHUB_CLIENT_SECRET")
GOOGLE_CLIENT_ID = config("GOOGLE_CLIENT_ID")
GOOGLE_CLIENT_SECRET = config("GOOGLE_CLIENT_SECRET")
SECRET_KEY = config("SECRET_KEY")
ZAI_API_KEY = config("ZAI_API_KEY")
GEMINI_API_KEY = config("GEMINI_API_KEY")

CLOUDINARY_CLOUD_NAME = config("CLOUDINARY_CLOUD_NAME")
CLOUDINARY_API_KEY = config("CLOUDINARY_API_KEY")
CLOUDINARY_API_SECRET =config("CLOUDINARY_API_SECRET")

